apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spekemat
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 12
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    path: /metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: spekemat-slakter
        - application: spleis-api
    outbound:
      rules:
        - application: spleis-api
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{databaseTier}}
        diskAutoresize: true
        databases:
          - name: spekemat
            envVarPrefix: DATABASE
  ingresses:
    - {{ingress}}
