apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spekemat
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 12
  liveness:
    path: /isalive
  readiness:
    path: /isready
    periodSeconds: 1
  resources:
    limits:
      memory: 1024Mi
  prometheus:
    path: /metrics
    enabled: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: spekemat-slakter
        - application: spleis-api
        - application: spoken
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: {{databaseTier}}
        diskAutoresize: true
        databases:
          - name: spekemat
            envVarPrefix: DATABASE
  ingresses:
    - {{ingress}}
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki

