apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spekemat-slakter
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 24
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: {{consumerGroupId}}
        threshold: 200
  liveness:
    path: /isalive
  readiness:
    path: /isready
  resources:
    limits:
      memory: 1024Mi
  prometheus:
    enabled: true
    path: /metrics
  preStopHook:
    http:
      path: /stop
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    outbound:
      rules:
        - application: spekemat
  azure:
    application:
      enabled: true
      tenant: nav.no
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{consumerGroupId}}
    - name: KAFKA_RESET_POLICY
      value: latest
  observability:
    logging:
      destinations:
        - id: elastic
