[versions]
sasGradlePlugins = "20260923.0907"
tbd-libs = "20260917.2152"

[libraries]
flyway-database-postgresql = "org.flywaydb:flyway-database-postgresql:13.7.0"
hikaricp = "com.zaxxer:HikariCP:7.1.0"
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
kotliquery = "com.github.seratch:kotliquery:1.9.1"
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic" }
logstash-logback-encoder = "net.logstash.logback:logstash-logback-encoder:8.0"
postgresql = "org.postgresql:postgresql:42.7.13"
rapids-and-rivers = "com.github.navikt:rapids-and-rivers:2026011411051768385145.e8ebad1177b4"
tbd-libs-azure-token-client-default = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbd-libs" }
tbd-libs-naisful-app = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbd-libs" }
tbd-libs-retry = { module = "com.github.navikt.tbd-libs:retry", version.ref = "tbd-libs" }

mockk = "io.mockk:mockk:1.13.17"
tbd-libs-mock-http-client = { module = "com.github.navikt.tbd-libs:mock-http-client", version.ref = "tbd-libs" }
tbd-libs-naisful-test-app = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbd-libs" }
tbd-libs-postgres-testdatabaser = { module = "com.github.navikt.tbd-libs:postgres-testdatabaser", version.ref = "tbd-libs" }
tbd-libs-rapids-and-rivers-test = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbd-libs" }

[plugins]
sas-deployable = { id = "no.nav.helse.sas.sas-deployable", version.ref = "sasGradlePlugins" }
sas-kotlin = { id = "no.nav.helse.sas.sas-kotlin", version.ref = "sasGradlePlugins" }
sas-root = { id = "no.nav.helse.sas.sas-root", version.ref = "sasGradlePlugins" }
