name: build foredler

on:
  push:
    branches:
      - main
    paths:
      - 'foredler/**'
      - 'fabrikk/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - '.github/workflows/foredler.yml'
      - '.nais/foredler.yml'
      - '.nais/foredler-dev.json'
      - '.nais/foredler-prod.json'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: gradle
        run: ./gradlew :foredler:build
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: foredler
          docker_context: foredler
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/foredler.yml
          VARS: .nais/foredler-dev.json
          IMAGE: ${{ needs.build.outputs.image }}
  deployProd:
    name: deploy to prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/foredler.yml
          VARS: .nais/foredler-prod.json
          IMAGE: ${{ needs.build.outputs.image }}